version: '3'
services :
  pg:
    image: postgres:10-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  admin:
    image: adminer
    restart: always
    links: 
      - pg:db
    ports:
      - 8080:8080
  web:
    build: .
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "5000:5000"
    links:
      - pg:api
    environment:
      HOST: api
      PORT: 5000
      SECRET: 'cursoHapi'
  